### ISSUE TITLE
Mobile Safari hangs on app load in private browsing mode

### ISSUE THREAD

**Issue by lewisl9029** [lewisl9029/toc#509]
Probably due to this https://github.com/thlorenz/convert-source-map/issues/31
Doesn't happen on release builds since those are minified and have comments stripped out.

**Comment by lewisl9029** [comment]
Never mind, according to @d22yan it's hanging on dev builds and release builds. Not seeing this on my iPad, but this iPad is still on iOS 8. 

Could be an issue specific to iOS 9. Or possibly due to some leftover incompatible data from previous versions?

I pushed a new debug branch to http://toc.im/releases/staging/bugfix-iphone-browser-load-hang to output errors directly to the screen. @d22yan could you take a screenshot of that page when you have the time?

**Comment by d22yan** [comment]
![image1](https://cloud.githubusercontent.com/assets/2700657/10840588/fa4c55ba-7e9d-11e5-9efa-6352b156faa7.png)
![image2](https://cloud.githubusercontent.com/assets/2700657/10840589/fa60f4b6-7e9d-11e5-966e-cbda67c30822.jpeg)

TOC splash screen didn't appear this time. There was nothing else on the screen even when I attempted to drag the screen up or down.

**Comment by lewisl9029** [comment]
Hmm that's weird. Only the test error is showing up. I honestly thought there would be more errors. Could it be that it just didn't finish loading yet? How long did you stay on this screen before taking the screenshot? This version is uncompressed so there's about 5MBs worth of JS and CSS that need to be downloaded, which might take a while even on 4G.

Anyways here's something else to try: I just pushed a change to the same branch. On the landing page there should be a "Clear local data" button. Just click that, wait for the page to refresh, and then go to /app and see if it can finish loading this time.

**Comment by d22yan** [comment]
The clear local data didn't refresh the page or me. It's still hanging on the toc splash page. Here's what I have tried.

1. http://toc.im/releases/staging/bugfix-iphone-browser-load-hang
2. clicked "clear local data" and waited about 20 seconds
3. enter /app
toc splash screen shows
4. waited for about 2mins
same screen with the 3 bouncing dots

**Comment by lewisl9029** [comment]
Turns out it was private browsing mode XD
Errors were occurring on local storage access.
